const fileTypes = {
  SET_FILTERS: 'SET_FILTERS',

  MOVE_ELEMENTS: 'MOVE_ELEMENTS',

  GET_FILE_LIST: 'GET_FILE_LIST',
  LOAD_FILE_LIST: 'LOAD_FILE_LIST',
  SET_FILE_LIST: 'SET_FILE_LIST',

  TRASH_ALERT_CLEAR: 'TRASH_ALERT_CLEAR',
  TRASH_ALERT: 'TRASH_ALERT',
  TRASH_RESTORE: 'TRASH_RESTORE',
  TRASH_DELETE: 'TRASH_DELETE',
  TRASH_SELECTED: 'TRASH_SELECTED',
  GET_TRASH_LIST: 'GET_TRASH_LIST',
  LOAD_TRASH_LIST: 'LOAD_TRASH_LIST',
  SET_TRASH_LIST: 'SET_TRASH_LIST',

  SET_DIRECTORY_PATH: 'SET_DIRECTORY_PATH',
  CREATE_NEW_FOLDER: 'CREATE_NEW_FOLDER',
  FOLDER_ALERT_ERROR: 'FOLDER_ALERT_ERROR',
  FOLDER_ALERT_SUCCESS: 'FOLDER_ALERT_SUCCESS',
  CLEAR_FOLDER_ALERTS: 'CLEAR_FOLDER_ALERTS',
  RENAME_ITEM: 'RENAME_ITEM',
  DELETE_ITEM: 'DELETE_ITEM',

  UPLOAD_FILE: 'UPLOAD_FILE',
  DOWNLOAD_ITEM: 'DOWNLOAD_ITEM',

  ALERT_INFO: 'ALERT_INFO',
  ALERT_CLEAR: 'ALERT_CLEAR',

  FOLDERS_PATH: 'FOLDERS_PATH',
  MOVE_FOLDER: 'MOVE_FOLDER',
  SELECT_FOLDER: 'SELECT_FOLDER',
  FOLDERS_CHECKED: 'FOLDERS_CHECKED',
  FILES_CHECKED: 'FILES_CHECKED',
  ITEM_SELECTED: 'ITEM_SELECTED',
  ITEM_CHECKED: 'ITEM_CHECKED',
  HANDLE_SELECTED: 'HANDLE_SELECTED',
};

export default fileTypes;
