const fileTypes = {
  GET_FILE_LIST: 'GET_FILE_LIST',
  LOAD_FILE_LIST: 'LOAD_FILE_LIST',
  SET_FILE_LIST: 'SET_FILE_LIST',
  GET_TRASH_LIST: 'GET_TRASH_LIST',
  LOAD_TRASH_LIST: 'LOAD_TRASH_LIST',
  SET_TRASH_LIST: 'SET_TRASH_LIST',
  SET_DIRECTORY_PATH: 'SET_DIRECTORY_PATH',

  CREATE_NEW_FOLDER: 'CREATE_NEW_FOLDER',
  FOLDER_ALERT_ERROR: 'FOLDER_ALERT_ERROR',
  FOLDER_ALERT_SUCCESS: 'FOLDER_ALERT_SUCCESS',
  CLEAR_FOLDER_ALERTS: 'CLEAR_FOLDER_ALERTS',
  RENAME_ITEM: 'RENAME_ITEM',
  DELETE_ITEM: 'DELETE_ITEM',

  UPLOAD_FILE: 'UPLOAD_FILE',
  DOWNLOAD_ITEM: 'DOWNLOAD_ITEM',

  FOLDERS_CHECKED: 'FOLDERS_CHECKED',
  FILES_CHECKED: 'FILES_CHECKED',
  ITEM_SELECTED: 'ITEM_SELECTED',
  ITEM_CHECKED: 'ITEM_CHECKED',
  HANDLE_SELECTED: 'HANDLE_SELECTED',

  RESTORE_ITEM: 'RESTORE_ITEM',
  PERM_DELETE: 'PERM_DELETE',
};

export default fileTypes;
