const fileTypes = {
  GET_FILE_LIST: 'GET_FILE_LIST',
  LOAD_FILE_LIST: 'LOAD_FILE_LIST',
  SET_FILE_LIST: 'SET_FILE_LIST',
  GET_TRASH_LIST: 'GET_TRASH_LIST',
  LOAD_TRASH_LIST: 'LOAD_TRASH_LIST',
  SET_TRASH_LIST: 'SET_TRASH_LIST',
  SET_DIRECTORY_PATH: 'SET_DIRECTORY_PATH',

  CREATE_NEW_FOLDER: 'CREATE_NEW_FOLDER',
  DELETE_FOLDER: 'DELETE_FOLDER',
  RENAME_FOLDER: 'RENAME_FOLDER',
  FOLDER_ALERT_ERROR: 'FOLDER_ALERT_ERROR',
  FOLDER_ALERT_SUCCESS: 'FOLDER_ALERT_SUCCESS',
  CLEAR_FOLDER_ALERTS: 'CLEAR_FOLDER_ALERTS',

  UPLOAD_FILE: 'UPLOAD_FILE',
  DOWNLOAD_FILE: 'DOWNLOAD_FILE',

  FOLDERS_CHECKED: 'FOLDERS_CHECKED',
  FILES_CHECKED: 'FILES_CHECKED',
  ITEM_SELECTED: 'ITEM_SELECTED',
};

export default fileTypes;
