const playlistTypes = {
  PLAY_FILE: 'PLAY_FILE',

  SET_ACTIVE_FILE: 'SET_ACTIVE_FILE',
  GET_FILE_DATA: 'GET_FILE_DATA',

  GET_PLAYLISTS: 'GET_PLAYLISTS',
  ADD_PLAYLIST: 'ADD_PLAYLIST',
  DELETE_PLAYLIST: 'DELETE_PLAYLIST',
  EDIT_PLAYLIST: 'EDIT_PLAYLIST',
  SET_PLAYLISTS: 'SET_PLAYLISTS',
};

export default playlistTypes;
