const playlistTypes = {
  PLAYLIST_FILES_SET: 'PLAYLIST_FILES_SET',
  PLAYLIST_FILES: 'PLAYLIST_FILES',

  PLAYLIST_SELECT_FILE: 'PLAYLIST_SELECT_FILE',
  PLAYLIST_ADD_FILE: 'PLAYLIST_ADD_FILE',
  PLAYLIST_DELETE_FILE: 'PLAYLIST_DELETE_FILE',

  PLAY_FILE: 'PLAY_FILE',

  SET_ACTIVE_FILE: 'SET_ACTIVE_FILE',
  GET_FILE_DATA: 'GET_FILE_DATA',

  GET_PLAYLISTS: 'GET_PLAYLISTS',
  ADD_PLAYLIST: 'ADD_PLAYLIST',
  DELETE_PLAYLIST: 'DELETE_PLAYLIST',
  EDIT_PLAYLIST: 'EDIT_PLAYLIST',
  SET_PLAYLISTS: 'SET_PLAYLISTS',
};

export default playlistTypes;
