const userTypes = {
  USER_LOGIN: 'USER_LOGIN',
  USER_SIGNUP: 'USER_SIGNUP',
  USER_LOADING: 'USER_LOADING',
  USER_DATA: 'USER_DATA',
  SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
  SIGNUP_CLEAR: 'SIGNUP_CLEAR',
  USER_ERROR: 'USER_ERROR',
  USER_CLEAR: 'USER_CLEAR',
  CHECK_USER_AUTHENTICATED: 'CHECK_USER_AUTHENTICATED',
  USER_LOADED: 'USER_LOADED',
  USER_LOGOUT: 'USER_LOGOUT',
};

export default userTypes;
